apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleservices.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: ConsoleService
    listKind: ConsoleServiceList
    singular: consoleservice
    plural: consoleservices
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            discoveryMetadataURL:
              type: string
            certificateSecret:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            oauthClientSecret:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            scope:
              type: string
            routeName:
              type: string
            serviceName:
              type: string
            deploymentName:
              type: string
            serviceAccountName:
              type: string
