apiVersion: v1
kind: Service
metadata:
  name: console
  annotations:
      service.alpha.openshift.io/serving-cert-secret-name: console-tls
  labels:
    app: enmasse
spec:
  ports:
  - name: web
    port: 443
    targetPort: 8443
  selector:
    name: global-console
